### ISSUE TITLE
Crash during dark Scan

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#14]
The software crashed after a scan was performed on a module in the dark (it would have no voltage) in %Voc mode.

**Comment by markbreynolds** [comment]
Can you post the log?

**Comment by nfehrenbach** [comment]
[ivscan-2017-03-03.txt](https://github.com/OneSunSolar/IVScan/files/817796/ivscan-2017-03-03.txt)

**Comment by markbreynolds** [comment]
The problem seems to be with calculating the Isc. In situations where the Isc cannot be calculated should we just use the measured Isc?

**Comment by nfehrenbach** [comment]
Yeah, I think that would be best.

**Comment by markbreynolds** [comment]
Fixed.
