### ISSUE TITLE
Automated Sweep Real Time Graphing

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#15]
The automated sweep graphs only appear after the entire set of sweeps has completed (ie after a cycle of the job has finished executing) Is there any way to have each sweep briefly appear between the sweeps in each job?

**Comment by markbreynolds** [comment]
Not sure why that isn't already happening. I added some extra logging to help figure out what is going on, I can test this next week.

**Comment by markbreynolds** [comment]
Seems to be fixed?
