### ISSUE TITLE
Holder Crash During Test

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#16]
Holder tool crashed when measuring at any time interval or voltage. Keithley was stuck in voltage source mode until output was turned off on the Keithley interface. Keithley dispayed "ERROR: ID CODE -102 \n Syntax Error". 
[ivscan-2017-03-07.txt](https://github.com/OneSunSolar/IVScan/files/826204/ivscan-2017-03-07.txt)

**Comment by nfehrenbach** [comment]
Ignore the other log, it was only the first crash.
[ivscan-2017-03-07.txt](https://github.com/OneSunSolar/IVScan/files/826219/ivscan-2017-03-07.txt)

**Comment by markbreynolds** [comment]
Fixed.
