### ISSUE TITLE
Newest .exe delays job onset

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#17]
The newest .exe (the one you sent on 3/7/17 with Holder v0.1) delays the onset of the automated sweep jobs until the cycle frequency time. ie I started a job with 12 hr cycles and it scheduled the first set of sweeps for 12 hours from when I commanded the job to begin.

**Comment by nfehrenbach** [comment]
[ivscan-2017-03-07.txt](https://github.com/OneSunSolar/IVScan/files/826239/ivscan-2017-03-07.txt)

**Comment by markbreynolds** [comment]
That .exe wasn't really production ready, I forgot to set a flag that made automation jobs actually do something. So the job actually started on time, the job just didn't do anything.
