### ISSUE TITLE
Wrong Extension for Summary

### ISSUE THREAD

**Issue by markbreynolds** [OneSunSolar/IVScan#2]
Summary files have the extension .csv when they should have .txt

**Comment by markbreynolds** [comment]
Unable to reproduce. Waiting for more information to see if reproducible.

**Comment by nfehrenbach** [comment]
I think there was some confusion. It is not that the files are csv files, it is that the string in the summary.txt file lists the individual IV files as .csv even though they are saved as .txt

**Comment by markbreynolds** [comment]
OK that makes more sense. I will check that out.

**Comment by nfehrenbach** [comment]
Extensions of IV files no reflect the saved format
