### ISSUE TITLE
crash after keithley SMU turned off

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#23]
The program crashed after trying to take a resistance measurement with the keithley turned off. It warned that it could not connect to the device. The SMU was turned back on, then the measurement attempted. It once again tried to scan. The SMU responded but no data was posted. The program then locked up and exited.
[ivscan-2017-07-13.txt](https://github.com/OneSunSolar/IVScan/files/1146030/ivscan-2017-07-13.txt)

**Comment by markbreynolds** [comment]
I couldn't reproduce this with the newest .exe, let me know if you can reproduce it with either the old one or the newest one.

**Comment by markbreynolds** [comment]
I was able to reproduce this error on the old software. So something must have gotten fixed since then.
