### ISSUE TITLE
Rear Terminal Inoperable

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#4]
When selecting either "- <- +" or "- <-> +" modes the sweep seems unable to complete in Rear Terminal mode. When in "- -> +" the rear terminal sweeps, but it seems like the Voc measurement does not go through the Rear Terminal (it may be taking a front terminal Voc reading than sweeping with the rear terminal). The issues disappear when you switch to the front terminals, so it is not a hardware error, and local measurements with the rear terminal render the correct voltage.

**Comment by markbreynolds** [comment]
I will look into both of these, but I highly suspect you are correct that it is measuring V<sub>oc</sub> through the front terminals.

**Comment by markbreynolds** [comment]
@nfehrenbach Can you send me the log files when you get a chance?

**Comment by markbreynolds** [comment]
V<sub>oc</sub> and I<sub>sc</sub> measurement should be done through the correct terminal now. It's just using the front terminals when using "- <- +" correct?

**Comment by nfehrenbach** [comment]
Rear terminal operates normally.
