### ISSUE TITLE
Efficiency and Fill Factor representation in IV Sweep.exe log and output files

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#5]
Best if the log and output files reflected the scan results section of the IV Sweep application. Currently the log displays efficiency as a proportion of 1 (eg 0.05) where the results section lists it as a percentage (eg 5%). We would like to see both Efficiency and Fill Factor reported as percentages in the log (also the summary and individual IV files) instead of as proportions of 1. (We prefer the 5% representation over 0.05)

**Comment by markbreynolds** [comment]
Fixed.
