### ISSUE TITLE
Job Saving

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#8]
New IV files are generated at the appropriate times, but are saved to the default location (Documents) despite the UI indicating they should be saved to a different directory. Additionally, no summary file was generated and the summary file in the user specified directory was not updated to include the new IV scans.

**Comment by markbreynolds** [comment]
Is this for manual or automatic sweeps?

**Comment by nfehrenbach** [comment]
It is for the automatic sweeps, I haven't tried a manual sweep, I can do one today and update you on what happens.

**Comment by nfehrenbach** [comment]
This is only for the automated sweeps, the manual IV saves to the correct directory.

**Comment by markbreynolds** [comment]
Ok I will fix this soon, I originally thought it wouldn't matter since it would just go to database so documents was a temporary solution.

**Comment by nfehrenbach** [comment]
Gotcha, I think since the database is still in its infancy we will continue to need hard copies. The newest exe does create a summary with all the correct data which is the most important part.

**Comment by markbreynolds** [comment]
Fixed
