### ISSUE TITLE
IV files for Automated Sweeps

### ISSUE THREAD

**Issue by nfehrenbach** [OneSunSolar/IVScan#9]
Efficiency in IV files now calculated incorrectly, not certain of error, however efficiency of 4.06 was reported as ~22,000.

**Comment by nfehrenbach** [comment]
Additionally, the temperature is reported wrong.

**Comment by nfehrenbach** [comment]
...and the irradience

**Comment by markbreynolds** [comment]
Should be fixed now. Once #8 is fixed I will send an .exe for testing.

**Comment by nfehrenbach** [comment]
Just updated #8 this issue is also only for the automated IV scans. All manual scans still output correct information.

**Comment by markbreynolds** [comment]
Great thank you, it was an issue with temperature and irradiance not being set for automated sweeps. I believe that without the proper irradiance, it is impossible to correctly calculate the efficiency, correct?

**Comment by markbreynolds** [comment]
Fixed.
